cricksite/cricksite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from teams import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^teams/', include('teams.urls')),
    url(r'^$', views.home, name='home')
]

cricksite/teams/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

from . import views

app_name = "teams"


urlpatterns = (
                  # /teams/
                  url(r'^$', views.index, name='index'),

                  # /teams/teamID
                  url(r'^(?P<teamID>[0-9]+)/$', views.details, name='details'),

                  # /teams/TeamID/Player
                  url(r'^(?P<teamID>[0-9]+)/players$', views.players, name='players'),
                  # /teams/add/
                  url(r'^add/$', views.TeamCreate.as_view(), name='Team-Add'),

                  # /teams/teamID/update/
                  url(r'^(?P<pk>[0-9]+)/update/$', views.TeamUpdate.as_view(), name='Team-Update'),

                  # /teams/teamID/delete/
                  url(r'^(?P<teamID>[0-9]+)/delete/$', views.teamdelete, name='Team-Delete'),

                  # /teams/add_player/
                  url(r'^add_player/$', views.PlayerCreate.as_view(), name='Player-Add'),

                  #/teams/players/pid/update/
                  url(r'^players/(?P<pk>[0-9]+)/update/$', views.PlayerUpdate.as_view(), name='Player-Update'),

                  #/teams/players/pid/delete/
                  url(r'^/players/(?P<pid>[0-9]+)/delete/$', views.playerdelete, name='Player-Delete'),


)

cricksite/teams/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Teams(models.Model):
    TeamID = models.IntegerField(primary_key=True)
    TeamName = models.CharField(max_length=50)
    TeamRank = models.IntegerField()

    def get_absolute_url(self):
        return reverse('teams:details', kwargs={'teamID': self.pk})

    def __str__(self):
        return self.TeamName


class Player(models.Model):
    TeamID = models.ForeignKey(Teams, on_delete=models.CASCADE)
    PID = models.IntegerField(primary_key=True)
    PName = models.CharField(max_length=100)
    PAge = models.IntegerField()
    PType = models.CharField(max_length=150)

    def get_absolute_url(self):
        return reverse('teams:index', kwargs={})

    def __str__(self):
        return self.PName

cricksite/teams/views.py
from django.shortcuts import render
from .models import Teams, Player
from django.http import Http404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


# Create your views here.
def index(request):
    context = {'all_teams': Teams.objects.all()}
    return render(request, 'teams/index.html', context)


def details(request, teamID):
    try:
        team: object = Teams.objects.get(pk=teamID)
    except Teams.DoesNotExist:
        raise Http404("Team is not registered")
    return render(request, 'teams/details.html', {'team': team})


def players(request, teamID):
    try:
        pl: object = Player.objects.filter(TeamID_id=teamID)
    except Player.DoesNotExist:
        raise Http404("No Registered Players in the Team")
    return render(request, 'teams/retplayers.html', {'pl': pl})


def home(request):
    return render(request, 'teams/home.html', {})


class TeamCreate(CreateView):
    model = Teams
    fields = ['TeamID', 'TeamName', 'TeamRank', ]


class TeamUpdate(UpdateView):
    model = Teams
    fields = ['TeamID', 'TeamName', 'TeamRank',]


def teamdelete(request, teamID):
    try:
        t: object = Teams.objects.filter(TeamID=teamID)
    except Player.DoesNotExist:
        raise Http404("Please Select a valid team to remove")
    deleted = t.delete()
    if deleted:
        return render(request, 'teams/delete_team__confirm.html', )
    else:
        raise Http404(" Sorry, we could not delete the given team")


class PlayerCreate(CreateView):
    model = Player
    fields = ['PID','TeamID', 'PName', 'PAge', 'PType', ]


class PlayerUpdate(UpdateView):
    model = Player
    fields = ['PID','TeamID', 'PName', 'PAge', 'PType', ]



def playerdelete(request, pid):
    try:
        t: object = Player.objects.filter(PID=pid)
    except Player.DoesNotExist:
        raise Http404("Please Select a valid player to remove")
    deleted = t.delete()
    if deleted:
        return render(request, 'teams/player_confirm_delete.html', )
    else:
        raise Http404(" Sorry, we could not delete the given team")

class Playerdelete(DeleteView):
    model = Player
    reverse_lazy('/teams/')

cricksite/teams/templates/teams/Player_form.html
{% extends 'teams/base.html'%}
{% block title%} Add New Team{% endblock %}
{% block teams_active %}active{% endblock %}
<h1>Player Details</h1>
{% block body%}
<div class="row">
    <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">
               <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                   {% csrf_token %}
                   {% include 'teams/form-template.html'%}
                   <div class="col-sm-offset-2 col-sm-10 ">
                       <button type="submit" class="btn btn-success">Submit<</button>
                   </div>


               </form>
            </div>
        </div>
    </div>
</div>


{% endblock%}

cricksite/teams/templates/teams/Teams_form.html
{% extends 'teams/base.html'%}
{% block title%} Add New Team{% endblock %}
{% block teams_active %}active{% endblock %}
<h1>Team Details</h1>
{% block body%}
<div class="row">
    <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">
               <form class="form-horizontal" action="/teams/" method="post" enctype="multipart/form-data">
                   {% csrf_token %}
                   {% include 'teams/form-template.html'%}
                   <div class="col-sm-offset-2 col-sm-10 ">
                       <button type="submit" class="btn btn-success">Submit<</button>
                   </div>


               </form>
            </div>
        </div>
    </div>
</div>


{% endblock%}

cricksite/teams/templates/teams/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CrickSite</title>
</head>

<body>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'teams/style.css' %}"/>
<link rel="stylesheet" href ="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css2?family=Tenali+Ramakrishna&display=swap" rel="stylesheet">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<nav class="navbar navbar-inverse">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="topNavBar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <div class="container-fluid">
        <!.. Logo ....!>
        <div class="navbar-header">
            <a class="navbar-brand" href="/">CrickSite</a>
        </div>
        <!..Items...!>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="/teams"> Teams</a>
                </li>
            </ul>
             <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
             <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="/teams/add/">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;New Team
                    </a>

                </li>
                 <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="/teams/add_player/">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;New Player
                    </a>

                </li>
                 <li class="active">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                    </a>

                </li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

cricksite/teams/templates/teams/delete_team_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Team Delete</title>
{% extends 'teams/base.html' %}
{% block body%}
</head>
<body>
<h1>Team Deleted Successfully</h1>
<a href="/teams/">Click Here to go back to teams homepage</a>
</body>
{% endblock %}
</html>

cricksite/teams/templates/teams/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Team Details</title>
{% extends 'teams/base.html' %}

<body>
{% block body%}

<h1> Team Details</h1>
<!....Team Logo...!>
<img src="{{team.TeamLogo.url}}">
<h2>{{team.TeamName}}</h2>
<h3>Team ID: {{team.TeamID}}</h3>
<h3>Team Rank: {{team.TeamRank}}</h3>
<br>
<a href="/teams/{{ team.TeamID }}/players">click to view team players</a><br>
<!...Add Player....!>
<form action="/teams/{{team.TeamID}}/add_player/" method="post" >
    {% csrf_token %}
    <input type="submit" value="Add Player" >
</form>
<br>
<!...Delete....!>
<form action="/teams/{{team.TeamID}}/delete/" method="post" >
    {% csrf_token %}
    <input type="submit" value="Delete Team" >
</form>
<br>
<!..Update...!>
<form action="/teams/{{team.TeamID}}/update/" method="get" >
    {% csrf_token %}
    <input type="submit" value="Update Details" >
</form>

{% endblock %}

</body>
</html>

cricksite/teams/templates/teams/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10 ">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor%}

cricksite/teams/templates/teams/home.html
{% extends 'teams/base.html' %}
<body>
{% block body%}
<div class=""container-fluid"">
<h1>All your Cricket Info at one place</h1>
<h2>Developers</h2>
<ul>
    <li>Himanshu V Dubara</li>
    <li>Jeet Rakesh Shah</li>

{% endblock %}
</ul>

</div>



</body>

cricksite/teams/templates/teams/index.html
{% extends 'teams/base.html' %}
{% block body%}
<h1> This is the Teams Homepage</h1>
{% for team in all_teams %}
<li><a href="/teams/{{ team.TeamID }}/">{{team.TeamName}}</a></li><br>


{% endfor %}
{% endblock %}

cricksite/teams/templates/teams/player_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Team Delete</title>
{% extends 'teams/base.html' %}
{% block body%}
</head>
<body>
<h1>Player Deleted Successfully</h1>
<a href="/teams/">Click Here to go back to teams homepage</a>
</body>
{% endblock %}
</html>

cricksite/teams/templates/teams/retplayers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Players </title>
</head>
{% extends 'teams/base.html' %}
<body>
{% block body%}


<h1>Players in the chosen Team</h1>

<table style="width:100%">

  <tr>
    <th colspan="20" style="text-align:center">Player ID</th>
    <th colspan="20" style="text-align:center">Player Name</th>
    <th colspan="20" style="text-align:center">Player Age</th>
    <th colspan="20" style="text-align:center">Player Type</th>
    <th colspan="20" style="text-align:center">Update</th>
    <th colspan="20" style="text-align:center">Delete</th>
  </tr>

  {% for p in pl %}
  <tr>
    <td colspan="20"  style="text-align:center">{{p.PID}}</td>
    <td colspan="20"  style="text-align:center">{{p.PName}}</td>
    <td colspan="20" style="text-align:center">{{p.PAge}}</td>
    <td colspan="20" style="text-align:center">{{p.PType}}</td>
    <td colspan="20" style="text-align:center">
      <form action="{% url 'teams:Player-Update' p.pk %}" method="get" >
    {% csrf_token %}
    <input type="submit" value="Update Details" >
</form>
    </td>
    <td colspan="20" style="text-align:center">
      <form action="{% url 'teams:Player-Delete' p.pk%}" method="get" >
    {% csrf_token %}
    <input type="submit" value="Delete Player" >
</form>
    </td>

  </tr>
  {% endfor %}

{% endblock %}
</body>
</html>